### ISSUE TITLE
ウェイクワード登録ファームウェアが作成/ダウンロードできない

### ISSUE THREAD

**Issue by shirouzu** [YUKAI/codama-doc-r0#4]
# 詳細
https://tools.codama.me/ において、4回の録音を行った上でアップロードボタンを押すも、30分以上待ってもダウンロードボタンが現れない。

# 環境
Win10 + Chrome最新版/Firefox最新版で確認。

# 備考
3週間前はビルド＆ダウンロードできました。

# 画像
（下記の状態のまま、変化がありません）
![image](https://user-images.githubusercontent.com/1759911/223381972-a583f138-f62f-48d5-a7a6-ff82ba8ce475.png)

**Comment by rtanote** [comment]
@shirouzu サーバが一部ダウンしておりました。再起動したのでお試しください。ご迷惑おかけいたします。

**Comment by shirouzu** [comment]
素早い対応、ありがとうございました。
無事使えるようになりました。
（なおサーバダウンの際は、その旨のエラーメッセージが出てくれるとより良いですね）
ともあれ、ありがとうございました。
