### ISSUE TITLE
USBマイクとして認識できない

### ISSUE THREAD

**Issue by shirouzu** [YUKAI/codama-doc-r0#5]
Codama が USBマイクとして認識できないのですが、対処法や確認点などがありましたら、教えて頂けないでしょうか。

# 詳細
- https://github.com/YUKAI/codama-doc-r0/wiki/WakeUpWord-With-Codama-PC
- 上記の手順を実施していますが、PC等からUSBマイクとして認識されません。
- （ファーム書き込み成功後、ジャンパーピンの取り外し、SDカード取り出し、リブートも実施しています）
- Win10PC以外に、MacBookAir、ラズパイ3 にUSB接続しても同様で、USBマイクとして認識されません。
- またUSBケーブルも複数本、交換しています。

# 環境
Win10、MacBookAir、ラズパイ3

# 備考
- 数週間前に一度だけ USBマイクとして認識されたのですが、https://github.com/YUKAI/codama-doc-r0/issues/4 で USBモードのウェイクワード用ファームを作成＆書き込んで以降、この状態です。
- 冒頭に書いたように codama/codama-doc-r0/firmware/update_usb.bin に書き戻しても、USBマイクとして認識されることが無くなりました。
- i2cモード用ファームを書き込めば、i2cモードとしては正しく動作します。

**Comment by KeitaIto123** [comment]
@shirouzu 
ユカイ工学のエンジニアの伊藤です。ご不便をおかけして申し訳ありません。
ご状況からですと、直接的な原因は推察しかねますが、こちら参考にしていただけるとありがたいです。

# codamaのセットアップに用いた環境
- Raspberry Pi 3 Model B, Raspberry Pi OS 32bit Bullseye (2023-02-21)
# ウェイクアップワード動作確認に用いた環境
- MacBookAir M1 2020, macOS Ventura version13.2

# 内容
- 以下の手順で試したところ、USBマイクとして認識され、ウェイクアップワードの動作確認ができたこと、共有させていただきます。
  - ~~基本的にはwikiに書いてある手順通りですが、検証の中で発覚した https://github.com/YUKAI/codama-doc-r0/issues/6 のエラーを回避するために、最新のraspberrypi-kernel-headersをinstallしないように手順を一部変更しています~~
  - ~~基本的にはwikiに書いてある手順通りですが、検証の中で発覚した #7 に対応するブランチに切り替えてからsetup.shを実行しています~~
- 試された手順と比較していただけると助かります。

## raspiのセットアップ
1. codamaをラズパイに取り付ける (白色のジャンパーピンは付けておく)
2. `git clone https://github.com/YUKAI/codama-doc-r0.git`
4. `sudo apt install -y libncurses5`
5. ~~`wget http://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/raspberrypi-kernel-headers_1.20230306-1_armhf.deb`~~
6. ~~`sudo dpkg -i raspberrypi-kernel-headers_1.20230306-1_armhf.deb`~~
7. `sudo apt install -y raspberrypi-kernel`
    - 更新があった場合、`sudo reboot`
9. `cd codama-doc-r0/codama-rpi-setup/`
10.  ~~setup.sh中の`sudo apt-get install -y raspberrypi-kernel-headers`の行を消す~~
11. ~~`git checkout fix/for_kernel_version6`~~
12. `./setup.sh`
13. `sudo reboot`
14. 録音のテスト
    - `arecord -c1 -fS16_LE -r16000 /tmp/test.wav`
    - `aplay -c1 -fS16_LE -r16000 /tmp/test.wav`

## ウェイクアップワードの作成
1. `cd ~/codama-doc-r0/firmware`
2. `codama_dfu_i2c write_upgrade update_usb.bin`
    - 失敗することが多いため、下記の成功するまで繰り返すスクリプトが便利です
```
#!/bin/bash

fail=true
while "$fail"
do
    codama_dfu_i2c write_upgrade $1
    if [ $? = 0 ]; then
        fail=false
    fi
done
```
4. Raspberry Piをシャットダウンし、電源を切る
5. SDカードをRaspberry Piから取り外す
6. codamaのジャンパーピンを外す
8. raspiに電源を入れる
10. codama の USB MiniBを、PCのUSB端子に接続する (データ通信用ケーブルを使用)
11. https://tools.codama.me/ にてUSB接続版のウェイクアップワード(update.bin)を作成
    - デフォルトだとI2C接続用を作成するため、USB接続の方を選択する
12. Raspberry Piの電源を抜き、codama をPCから外す
13. SDカードをRaspberry Piに取りつけ、codamaに白色のジャンパーピンを取り付け、raspiを起動

## ウェイクアップワードの書き込み/検証
1. ダウンロードしたupdate.binをRaspberry Piに配置
2. `codama_dfu_i2c write_upgrade update.bin`
    - ここでも上で紹介した成功するまで繰り返すスクリプトが便利です
3. Raspberry Piをシャットダウン
4. SDカードを抜く
6. ジャンパーピンを外す
7. Raspberry Piの電源を投入
8. PCとcodamaのUSBポートをUSBケーブルで繋ぐ 
9. PC側でウェイクアップワードの動作確認をする
```
$ mkdir codama
$ cd codama
$ git clone https://github.com/YUKAI/codama-doc-r0.git
$ pip3 install pyusb # PythonでUSBを動かすライブラリをインストール
$ cd ~/codama/codama-doc-r0/utils
$ while true; do sleep 0.2s; python3 codama_usb.py KEYWORDDETECT ;done
```

# お願い
- また参考のため、ラズパイでの下記のコマンドの実行結果を教えていただけると嬉しいです
```
$ uname -a 
$ sudo apt list --installed | grep kernel
```

**Comment by shirouzu** [comment]
とりいそぎき、uname -a と apt list の結果を添付いたします。
（お書き頂いた手順での検証は別途行ってみます）
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 5.15.84-v7+ #1613 SMP Thu Jan 5 11:59:48 GMT 2023 armv7l GNU/Linux
pi@raspberrypi:~ $ sudo apt list --installed | grep kernel
raspberrypi-kernel-headers/stable,now 1:1.20230106-1 armhf [インストール済み]
raspberrypi-kernel/stable,now 1:1.20230106-1 armhf [インストール済み]
```

**Comment by shirouzu** [comment]
raspiのセットアップを実施しようとしたところ、
9. git checkout fix/for_kernel_version6
は下記のエラーとなりました。
```
pi@raspberrypi:~ $ cd codama-doc-r0/codama-rpi-setup/
pi@raspberrypi:~/codama-doc-r0/codama-rpi-setup $ git checkout fix/for_kernel_version6
error: pathspec 'fix/for_kernel_version6' did not match any file(s) known to git
```
そこはskipして残項目を実行した後、ウェイクアップワードの作成を実施しようとしましたが、PC（Windows & Mac）に接続した時点で USBマイクとして認識されない状況のままでした。

何かが壊れてしまっているのですかね…

**Comment by KeitaIto123** [comment]
> raspiのセットアップを実施しようとしたところ、
> 9. git checkout fix/for_kernel_version6
> は下記のエラーとなりました。

以前の回答後に、fix/for_kernel_version6をmasterにマージしましたので、こちらの手順は飛ばしていただいて問題ありません。

> そこはskipして残項目を実行した後、ウェイクアップワードの作成を実施しようとしましたが、PC（Windows & Mac）に接続した時点で USBマイクとして認識されない状況のままでした。
> 何かが壊れてしまっているのですかね…
> 

おそらく以下のハードウェア的な問題が考えられます。
- codamaの基板上のUSBコネクタの接触不良
- ご使用されているUSBケーブルがデータ通信用ケーブルでない

前者に関して、代品の発送をもって対応させていただきます。
お手数ですが、https://codama.ux-xu.com/ に記載されているこちらの連絡先(contact@ux-xu.com)に、「codamaサポート宛」として、お名前と発送先をお送りしていただけるとありがたいです。

**Comment by shirouzu** [comment]
ありがとうございます。
最初にも書いた通り、USBケーブルは複数試していますのでケーブルの問題ではないと思っています。
サポート宛にご連絡させていただきます。
